server:
  port: 8085
  ssl:
    enabled: true
    key-store: /Users/a/Downloads/musicband-service/service-grammy/src/main/resources/keystore.p12
    key-store-password: yourpassword
    key-store-type: PKCS12
    key-alias: myapp
    protocols: TLSv1.2,TLSv1.3
spring:
  application:
    name: api-gateway

  cloud:
    discovery:
      enabled: true

    service-registry:
      enabled: false
      auto-registration:
        enabled: false

    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: false

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: false # регистрируем в eureka
  server:
    eviction-interval-timer-in-ms: 10000
zuul:
  routes:
    grammy:
      path: /api/grammy/**
      serviceId: SERVICE-GRAMMY
      strip-prefix: false

SERVICE-GRAMMY:
  ribbon:
    eager-load:
      clients: SERVICE-GRAMMY
    ServerListRefreshInterval: 100 # 0,1 с обновление списка
    PingUrl: /actuator/health # тк по умолчанию пингует /
    NFLoadBalancerPingInterval: 2000
    NFLoadBalancerPingClassName: com.netflix.loadbalancer.PingUrl

logging:
  level:
    root: INFO
    example.GrammyService: DEBUG
    example.GrammyResource: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    com.netflix.loadbalancer.LoadBalancerContext: DEBUG

